apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: second
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "second",
      "type": "host-device",
      "device": "eth10",
      "ipam": {
        "type": "static",
        "addresses": [
          {"address": "192.168.126.10/24"}
        ]
      }
    }
