kind: Pod
apiVersion: v1
metadata:
  name: busybox-storage
spec:
  containers:
  - name: my-busybox-1
    image: busybox:1.28
    volumeMounts:
      - mountPath: "/data"
        name: data
    command: [ "sleep", "1000000" ]

  - name: my-busybox-2
    image: busybox:1.28
    volumeMounts:
      - mountPath: "/data"
        name: data
    command: [ "sleep", "1000000" ]  

  volumes:
    - name: data
      emptyDir: {}
