apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-view-projects
rules:
  - apiGroups: [""]  # "" indicates the core API group (for resources like pods, services, etc.)
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - "!openshift-*"

